# Generated by Django 5.2.7 on 2025-11-01 06:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMember',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('primer_apellido', models.CharField(max_length=120)),
                ('segundo_apellido', models.CharField(blank=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grado', models.CharField(choices=[('APR', 'Aprendiz'), ('COM', 'Compañero'), ('MAE', 'Maestro')], max_length=3)),
                ('fecha_iniciacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('SUE', 'En sueños')], default='ACT', max_length=3)),
                ('numero_registro', models.CharField(db_index=True, max_length=50)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254)),
                ('numero_celular', models.CharField(blank=True, max_length=30)),
                ('domicilio_particular', models.TextField(blank=True)),
                ('domicilio_trabajo', models.TextField(blank=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=30)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=180)),
                ('contacto_emergencia_relacion', models.CharField(blank=True, max_length=80)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=30)),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rls', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='miembro', to='rls.rls')),
            ],
            options={
                'verbose_name': 'historical member',
                'verbose_name_plural': 'historical members',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('primer_apellido', models.CharField(max_length=120)),
                ('segundo_apellido', models.CharField(blank=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grado', models.CharField(choices=[('APR', 'Aprendiz'), ('COM', 'Compañero'), ('MAE', 'Maestro')], max_length=3)),
                ('fecha_iniciacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('SUE', 'En sueños')], default='ACT', max_length=3)),
                ('numero_registro', models.CharField(max_length=50, unique=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254)),
                ('numero_celular', models.CharField(blank=True, max_length=30)),
                ('domicilio_particular', models.TextField(blank=True)),
                ('domicilio_trabajo', models.TextField(blank=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=30)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=180)),
                ('contacto_emergencia_relacion', models.CharField(blank=True, max_length=80)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='miembros/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', related_query_name='miembro', to='rls.rls')),
            ],
            options={
                'ordering': ['rls', 'primer_apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('primer_apellido', models.CharField(max_length=120)),
                ('segundo_apellido', models.CharField(blank=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('domicilio', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('relacion', models.CharField(choices=[('conyuge', 'Cónyuge'), ('hijo', 'Hijo/a'), ('padre', 'Padre/Madre'), ('otro', 'Otro')], max_length=20)),
                ('porcentaje', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='miembros.member')),
            ],
        ),
        migrations.CreateModel(
            name='CargoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miembros.cargo')),
                ('rls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rls.rls')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_hist', to='miembros.member')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('miembro',), name='un_cargo_vigente_por_miembro')],
            },
        ),
    ]
