# Generated by Django 5.2.7 on 2025-11-24 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
        ('rls', '0002_alter_rls_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmember',
            name='rls',
        ),
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'ordering': ['member', 'nombre_completo'], 'verbose_name': 'Beneficiario', 'verbose_name_plural': 'Beneficiarios'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nombre'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='cargohistorico',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Historial de cargo', 'verbose_name_plural': 'Historial de cargos'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['rls__nombre', 'primer_apellido', 'nombre']},
        ),
        migrations.RemoveConstraint(
            model_name='cargohistorico',
            name='un_cargo_vigente_por_miembro',
        ),
        migrations.RenameField(
            model_name='beneficiario',
            old_name='miembro',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='relacion',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='cargohistorico',
            name='miembro',
        ),
        migrations.RemoveField(
            model_name='cargohistorico',
            name='rls',
        ),
        migrations.RemoveField(
            model_name='member',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contacto_emergencia_nombre',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contacto_emergencia_relacion',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contacto_emergencia_telefono',
        ),
        migrations.RemoveField(
            model_name='member',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nombre_completo',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='relacion',
            field=models.CharField(blank=True, choices=[('CONYUJE', 'Cónyuge'), ('HIJO', 'Hijo/a'), ('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HERMANO', 'Hermano/a'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cargohistorico',
            name='member',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='historial_cargos', to='miembros.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='cargo_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros_actuales', to='miembros.cargo'),
        ),
        migrations.AddField(
            model_name='member',
            name='correo_alterno',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo alterno'),
        ),
        migrations.AddField(
            model_name='member',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergencia_domicilio',
            field=models.TextField(blank=True, verbose_name='Domicilio contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergencia_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergencia_relacion',
            field=models.CharField(choices=[('CONYUJE', 'Cónyuge'), ('HIJO', 'Hijo/a'), ('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HERMANO', 'Hermano/a'), ('OTRO', 'Otro')], default='OTRO', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='emergencia_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergencia_telefono_alterno',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono alterno contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='member',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='member',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones (alergias, datos importantes)'),
        ),
        migrations.AddField(
            model_name='member',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, help_text='Ejemplo: O+, A-, B+', max_length=3, verbose_name='Tipo sanguíneo'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='porcentaje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='member',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='member',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('SUE', 'En sueños'), ('RET', 'Retirado')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='fecha_iniciacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de iniciación'),
        ),
        migrations.AlterField(
            model_name='member',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='miembros/fotos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='grado',
            field=models.CharField(choices=[('AP', 'Aprendiz'), ('CP', 'Compañero'), ('MM', 'Maestro'), ('PM', 'Pass Master')], default='AP', max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='numero_registro',
            field=models.CharField(blank=True, help_text='Se asignará automáticamente.', max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='primer_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='rls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miembros', to='rls.rls'),
        ),
        migrations.AlterField(
            model_name='member',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='HistoricalMember',
        ),
    ]
