# Generated by Django 5.2.7 on 2025-11-24 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_remove_historicalmember_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiario',
            options={},
        ),
        migrations.RenameField(
            model_name='beneficiario',
            old_name='relacion',
            new_name='relacion',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='domicilio',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='primer_apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='segundo_apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='member',
            field=models.ForeignKey(db_column='miembro_id', on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='miembros.member'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='beneficiario',
            table='miembros_beneficiario',
        ),
    ]
