# Generated by Django 5.2.7 on 2025-10-29 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('cuota', 'Cuota'), ('donacion', 'Donación'), ('aporte', 'Aporte')], max_length=12)),
                ('periodo', models.CharField(help_text='Ej. 2025-10 o 2025-T4', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('comprobante_pdf', models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('rls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='rls.rls')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
