# Generated by Django 5.2.7 on 2025-11-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('miembros', '0002_remove_historicalmember_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='comprobante_pdf',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='periodo',
        ),
        migrations.AddField(
            model_name='pago',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PAG', 'Pagado'), ('CAN', 'Cancelado')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='pago',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='miembros.member'),
        ),
    ]
