# Generated by Django 5.2.7 on 2025-10-28 19:55

import django.db.models.deletion
import mediax.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(max_length=80)),
                ('archivo', models.FileField(upload_to=mediax.models.doc_path)),
                ('visibilidad', models.CharField(choices=[('publico', 'Público'), ('miembros', 'Solo miembros'), ('oficiales', 'Solo oficiales')], default='miembros', max_length=12)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('etiquetas', models.CharField(blank=True, max_length=180)),
                ('rls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='rls.rls')),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('archivo', models.ImageField(upload_to=mediax.models.img_path)),
                ('visibilidad', models.CharField(choices=[('publico', 'Público'), ('miembros', 'Solo miembros'), ('oficiales', 'Solo oficiales')], default='publico', max_length=12)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('etiquetas', models.CharField(blank=True, max_length=180)),
                ('rls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes', to='rls.rls')),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
