# Generated by Django 5.2.7 on 2025-11-24 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rls', '0002_alter_rls_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ORD', 'Ordinaria'), ('EXT', 'Extraordinaria'), ('INST', 'Instalación'), ('ESP', 'Especial')], default='ORD', max_length=10)),
                ('grado', models.CharField(choices=[('APR', 'Aprendiz'), ('COM', 'Compañero'), ('MAE', 'Maestro')], default='APR', max_length=3)),
                ('tema', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenidas', to='rls.rls')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('tenida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='meetings.tenida')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('tenida', 'miembro')},
            },
        ),
    ]
