# Generated by Django 5.2.7 on 2025-11-26 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('rls', '0002_alter_rls_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['miembro'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AlterModelOptions(
            name='tenida',
            options={'ordering': ['-fecha'], 'verbose_name': 'Tenida', 'verbose_name_plural': 'Tenidas'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='puesto',
            field=models.CharField(choices=[('VM', 'Venerable Maestro'), ('PV', 'Primer Vigilante'), ('SV', 'Segundo Vigilante'), ('OR', 'Orador'), ('SE', 'Secretario'), ('TE', 'Tesorero'), ('MC', 'Maestro de Ceremonias'), ('EX', 'Experto'), ('GT', 'Guarda Templo'), ('HI', 'Hospitalario'), ('JD', 'Sin Cargo (Columna)'), ('VI', 'Visitante')], default='JD', max_length=3, verbose_name='Puesto del Día'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to=settings.AUTH_USER_MODEL, verbose_name='Hermano'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Ej: Llegó tarde, se retiró temprano', max_length=255),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=True, verbose_name='¿Asistió?'),
        ),
        migrations.AlterField(
            model_name='tenida',
            name='rls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenidas', to='rls.rls', verbose_name='R.L.S.'),
        ),
        migrations.AlterField(
            model_name='tenida',
            name='tipo',
            field=models.CharField(choices=[('ORD', 'Ordinaria'), ('EXT', 'Extraordinaria'), ('INST', 'Instalación'), ('ESP', 'Especial'), ('FUN', 'Fúnebre'), ('BLA', 'Tenida Blanca')], default='ORD', max_length=10),
        ),
    ]
