# Generated by Django 5.2.7 on 2025-10-29
# H:\FeyEsp2.0\fye_site\accounts\migrations\0003_cargo_alter_user_options_remove_user_rls_scope_and_more.py
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_numero_registro(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    seen = set()
    for u in User.objects.all().order_by("id"):
        nr = (getattr(u, "numero_registro", "") or "").strip()
        if not nr or nr in seen:
            nr = f"FYE{u.id:05d}"
        seen.add(nr)
        # Actualiza directo en DB para evitar validaciones adicionales
        User.objects.filter(pk=u.pk).update(numero_registro=nr)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("rls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["rls", "last_name", "first_name"],
                "verbose_name": "Miembro",
                "verbose_name_plural": "Miembros",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="rls_scope",
        ),
        migrations.AddField(
            model_name="user",
            name="correo_alterno",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Correo alterno"),
        ),
        migrations.AddField(
            model_name="user",
            name="estado",
            field=models.CharField(choices=[("ACT", "Activo"), ("SUE", "En sueños")], default="ACT", max_length=3),
        ),
        migrations.AddField(
            model_name="user",
            name="fecha_iniciacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="miembros/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="user",
            name="grado",
            field=models.CharField(choices=[("APR", "Aprendiz"), ("COM", "Compañero"), ("MAE", "Maestro")], default="APR", max_length=3),
        ),
        migrations.AddField(
            model_name="user",
            name="numero_celular",
            field=models.CharField(blank=True, max_length=30, verbose_name="Celular"),
        ),
        # 👇 Añadimos numero_registro de forma PERMISIVA y con default temporal
        migrations.AddField(
            model_name="user",
            name="numero_registro",
            field=models.CharField(max_length=50, null=True, blank=True, default="TEMP", verbose_name="Número de registro"),
            preserve_default=False,  # el default no queda persistido en DB tras crear la columna
        ),
        # 👇 Rellenamos valores únicos para todos los usuarios existentes
        migrations.RunPython(backfill_numero_registro, migrations.RunPython.noop),
        # 👇 rls temporalmente permisivo para no romper FKs mientras normalizas datos
        migrations.AddField(
            model_name="user",
            name="rls",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="miembros",
                to="rls.rls",
                verbose_name="RLS",
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="second_surname",
            field=models.CharField(blank=True, max_length=120, verbose_name="Segundo apellido"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Correo electrónico"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=120, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=120, verbose_name="Primer apellido"),
        ),
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=120)),
                ("primer_apellido", models.CharField(max_length=120)),
                ("segundo_apellido", models.CharField(blank=True, max_length=120)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("domicilio", models.TextField(blank=True)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("relacion", models.CharField(choices=[("conyuge", "Cónyuge"), ("hijo", "Hijo/a"), ("padre", "Padre/Madre"), ("otro", "Otro")], max_length=20)),
                ("porcentaje", models.PositiveIntegerField(blank=True, null=True)),
                ("miembro", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="beneficiarios", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Beneficiario",
                "verbose_name_plural": "Beneficiarios",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="cargo_actual",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="titulares", to="accounts.cargo"),
        ),
        migrations.CreateModel(
            name="CargoHistorico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("cargo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="accounts.cargo")),
                ("miembro", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cargos_hist", to=settings.AUTH_USER_MODEL)),
                ("rls", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cargos_hist_accounts", to="rls.rls")),
            ],
            options={
                "verbose_name": "Cargo histórico",
                "verbose_name_plural": "Cargos históricos",
                "ordering": ["-fecha_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("fecha_fin__isnull", True)),
                        fields=("miembro",),
                        name="un_cargo_vigente_por_miembro_accounts",
                    )
                ],
            },
        ),
    ]
