# Generated by Django 5.2.7 on 2025-10-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cargo_alter_user_options_remove_user_rls_scope_and_more'),
        ('rls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_registro',
            field=models.CharField("Número de registro", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rls',
                field=models.ForeignKey(
        on_delete=models.PROTECT,
        related_name='miembros',
        to='rls.rls',
        verbose_name='RLS',
        null=False,
        blank=False,
    ),
        ),
    ]
