# Generated by Django 5.2.7 on 2025-10-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_numero_registro_alter_user_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_registro',
            field=models.CharField(default='TEMP', max_length=20, unique=True, verbose_name='Número de Registro'),
        ),
    ]
