# Generated by Django 5.2.7 on 2025-11-01 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_numero_registro'),
        ('rls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', related_query_name='usuario', to='rls.rls'),
        ),
    ]
