# Generated by Django 5.2.7 on 2025-11-05 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_rls'),
        ('rls', '0002_alter_rls_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_registro',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='rls.rls', verbose_name='RLS'),
        ),
    ]
