# Generated by Django 5.2.7 on 2025-10-28 19:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRLS',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('numero', models.CharField(max_length=30)),
                ('homenaje_a', models.CharField(blank=True, max_length=180)),
                ('dia_que_trabaja', models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12)),
                ('hora_que_trabaja', models.TimeField(blank=True, null=True)),
                ('lugar', models.TextField(blank=True)),
                ('oriente', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rls',
                'verbose_name_plural': 'historical rlss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('numero', models.CharField(max_length=30)),
                ('homenaje_a', models.CharField(blank=True, max_length=180)),
                ('dia_que_trabaja', models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12)),
                ('hora_que_trabaja', models.TimeField(blank=True, null=True)),
                ('lugar', models.TextField(blank=True)),
                ('oriente', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['oriente', 'numero'],
                'unique_together': {('numero', 'oriente')},
            },
        ),
    ]
