# Generated by Django 5.2.7 on 2025-11-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rls',
            options={'ordering': ['nombre', 'numero']},
        ),
        migrations.RenameField(
            model_name='rls',
            old_name='hora_que_trabaja',
            new_name='hora_trabajo',
        ),
        migrations.AlterUniqueTogether(
            name='rls',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rls',
            name='dia_trabajo',
            field=models.CharField(blank=True, choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='rls',
            name='homenaje_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rls',
            name='lugar',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='rls',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rls',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='HistoricalRLS',
        ),
        migrations.RemoveField(
            model_name='rls',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='rls',
            name='dia_que_trabaja',
        ),
        migrations.RemoveField(
            model_name='rls',
            name='oriente',
        ),
    ]
